#include "secrets.h"
#include "esp_log.h"
#include "esp_http_client.h"

static const char *TAG = "Upload";

void upload_sensor_data(char* sensor_name, char* friendly_sensor_name, char* units, float data) {
    // Create API URL. Will look something like http://HA_URL/api/states/sensor.SENSOR_NAME
    char api_URL[256];
    snprintf(api_URL, 256, "%s/api/states/sensor.%s", HA_URL, sensor_name);
    
    // Create API request to home assistant with sensor data  
    char api_req[256];
    snprintf(api_req, 256, "{\"state\": \"%.2f\", \"attributes\": {\"unit_of_measurement\": \"%s\", \"friendly_name\": \"%s\"}}", data, units, friendly_sensor_name);

    // Long-Lived Access Token for Home Assistant API. This is generated by an administrator and is valid for 10 years. 
    const char* bearer = "Bearer ";
    char* auth_data = pvPortMalloc(strlen(bearer) + sizeof(LONG_LIVED_ACCESS_TOKEN));
    if(!auth_data) {
        ESP_LOGE(TAG, "auth_data malloc failed.");
        return;
    }
    memcpy(auth_data, bearer, strlen(bearer));
    memcpy(auth_data + strlen(bearer), LONG_LIVED_ACCESS_TOKEN, sizeof(LONG_LIVED_ACCESS_TOKEN));


    // Attempt to make API request to Home Assistant
    esp_http_client_config_t home_assistant_config = {
        .url = api_URL,
        .method = HTTP_METHOD_POST,
        .timeout_ms = 1500,
        .is_async = false,
        .skip_cert_common_name_check = true,
        .disable_auto_redirect = false,
    };

    esp_http_client_handle_t client = esp_http_client_init(&home_assistant_config);
    esp_http_client_set_header(client, "Authorization", auth_data);
    esp_http_client_set_header(client, "Content-Type", "application/json");
    esp_http_client_set_post_field(client, api_req, strlen(api_req));

    if(esp_http_client_perform(client) == ESP_OK){
        ESP_LOGI(TAG, "Sent %s to %s", api_req, api_URL);
    } else {
        ESP_LOGE(TAG, "Could not send upload sensor data.");
    }

    esp_http_client_close(client);
    esp_http_client_cleanup(client);
}
